'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'#'}catch{return '#'}};
const AZ={timeZone:'America/Phoenix'};
const fmt=s=>s?new Date(s).toLocaleString('en-US',{...AZ,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not available';
const time=s=>s?new Date(s).toLocaleTimeString('en-US',{...AZ,hour:'numeric',minute:'2-digit'}):'—';
const timeS=s=>s?new Date(s).toLocaleTimeString('en-US',{...AZ,hour:'numeric',minute:'2-digit',second:'2-digit'}):'—';
const azDate=s=>new Date(s).toLocaleDateString('en-CA',AZ);
const ago=s=>{if(!s)return '';const m=Math.round((Date.now()-new Date(s))/60000);return m<1?'just now':m<60?m+' min ago':Math.round(m/60)+' h ago'};
const am=v=>v==null?'—':(v>0?'+':'')+Math.round(v);
const stateName=s=>({FUT:'Upcoming',PRE:'Pregame',LIVE:'In progress',CRIT:'In progress',OFF:'Final',FINAL:'Final'})[s]||s||'Unknown';
const empty=(title,note)=>`<div class="empty"><strong>${esc(title)}</strong>${esc(note)}</div>`;
const token=()=>document.querySelector('meta[name=refresh-token]').content;
let data=null,parlays=null,boxRequest=0,refreshTimer=null;
const pageInfo={lineups:['Every line, in focus.','Complete forward-line reports, organized by team.','Lines'],
  parlays:['Parlays worth a look.','Goal + two assists + own-team under, priced on both books.','Parlays'],
  games:['The game starts here.','Upcoming games, lineup status, scores and box scores.','Upcoming'],
  results:['How they played out.','Tracked combinations, leg by leg, from official NHL statistics.','Results'],
  history:['What JuneBot checked.','Lineup scans, report changes, sportsbook checks and alerts.','History'],
  sources:['A clear view of the data.','What is connected, what is not, and when it was last checked.','Status']};
function page(){const id=location.hash.slice(1);return pageInfo[id]?id:'lineups'}
function showPage(){const id=location.hash.slice(1);if(id==='main')return;const p=page();document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===p)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});Object.keys(pageInfo).forEach(k=>$(k+'Page').classList.toggle('hidden',k!==p));$('pageTitle').textContent=pageInfo[p][0];$('pageSubtitle').textContent=pageInfo[p][1];document.title='JuneBot · '+pageInfo[p][2];window.scrollTo({top:0,behavior:'auto'});loadPage()}
window.addEventListener('hashchange',showPage);
// ---- Public read-only mode (the GitHub-hosted copy): same UI, data comes from JuneBot's published snapshot.
const PUB=window.JUNEBOT_PUBLIC||null;let PUBDATA=null,pubAt=0,pubLoading=null;
if(PUB){document.body.classList.add('public');try{PUBDATA=JSON.parse(localStorage.getItem('jb-pub')||'null')}catch{}}
async function pubFetch(){
 try{const r=await fetch('https://api.github.com/gists/'+PUB.gist,{cache:'no-store'});if(!r.ok)throw Error('api '+r.status);const g=await r.json();const f=g.files['data.json'];
  const c=f.truncated?await (await fetch(f.raw_url,{cache:'no-store'})).text():f.content;return JSON.parse(c)}
 catch(e){const r=await fetch(`https://gist.githubusercontent.com/${PUB.login}/${PUB.gist}/raw/data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Live data unavailable');return JSON.parse(await r.text())}}
async function pubLoad(){if(PUBDATA&&Date.now()-pubAt<50000)return PUBDATA;if(!pubLoading)pubLoading=pubFetch().then(d=>{PUBDATA=d;pubAt=Date.now();try{localStorage.setItem('jb-pub',JSON.stringify(d))}catch{}return d}).finally(()=>{pubLoading=null});
 try{return await pubLoading}catch(e){if(PUBDATA)return PUBDATA;throw e}}
function pubAge(){return PUBDATA&&PUBDATA.published_at?(Date.now()-new Date(PUBDATA.published_at))/60000:Infinity}
async function pubGet(path){const d=(PUBDATA&&!pubAt)?(pubLoad(),PUBDATA):await pubLoad();
 if(path==='')return Object.assign({},d.hockey,{published_at:d.published_at,mac:d.mac});
 if(path==='/parlays')return d.parlays;if(path==='/history')return d.history;if(path==='/results')return d.results;
 if(path.startsWith('/combo/')){const r=(d.parlays.rows||[]).find(x=>x.id===path.split('/').pop());return{quotes:[],stats:(r&&r.stats)||{timeline:[]}}}
 if(path.startsWith('/boxscore/')){const b=(d.boxscores||{})[path.split('/').pop()];if(!b)throw Error('Box score not published yet for this game');return b}
 throw Error('Not available on the public board')}
async function get(path){if(PUB)return pubGet(path);const r=await fetch('/api/hockey'+path,{cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'Data unavailable');return body}
async function post(path,body){const r=await fetch('/api/hockey'+path,{method:'POST',headers:{'X-Refresh-Token':token(),'Content-Type':'application/json'},body:JSON.stringify(body||{})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b}
function usable(r){const lines=r.lines||[];return !r.review_reasons?.length&&[3,4].includes(lines.length)&&lines.every(l=>l.players.length===3&&l.players.every(p=>['C','L','R','LW','RW','F'].includes(p.position)&&p.team===r.team))}
const kindBadge=k=>k==='practice'?'<span class="badge practice">PRACTICE</span>':k==='projected'?'<span class="badge practice">PROJECTED · DAILY FACEOFF</span>':'<span class="badge">REPORTED</span>';

// ------------------------------------------------------------- header + lines
function renderTop(){if(!data)return;const today=azDate(Date.now());const todays=data.games.filter(g=>azDate(g.start_time)===today);const teams=new Set(todays.flatMap(g=>[g.home,g.away]));const valid=data.reports.filter(usable);const c=data.counts||{};
$('reportCount').textContent=valid.length;$('comboCount').textContent=c.combinations??'—';$('comboNote').textContent=c.priced_both!=null?`${c.priced_both} priced at both books`:'6 per forward line';
$('qualCount').textContent=c.qualifying??'—';$('qualNote').textContent=(c.fire?`${c.fire} 🔥 Fire (3×+)`:'bet365 ≥ 1.8× FanDuel')+(c.unconfirmed?` · ${c.unconfirmed} unconfirmed`:'');$('navQual').textContent=c.qualifying||'';$('navQual').classList.toggle('hidden',!c.qualifying);
$('checkTime').textContent=time(data.updated_at);const stale=!data.updated_at||Date.now()-new Date(data.updated_at).getTime()>420000;$('freshness').textContent=stale?'Waiting for a fresh scan':'Checks every 2–5 minutes';
$('health').classList.toggle('hidden',!data.error&&!stale);$('health').textContent=data.error?'Source refresh failed. Showing the last available data. '+data.error:!data.updated_at?'Waiting for the first source check.':'The source snapshot is older than seven minutes. Refresh to check for updates.';
if(PUB){const age=pubAge(),off=data.mac==='stopped'||age>5;const pill=$('livePill');pill.classList.remove('hidden');pill.className='live-pill '+(off?'off':'on');
 pill.innerHTML=`<span class="dot ${off?'off':'on'}"></span>${off?(data.mac==='stopped'?'JuneBot stopped':'Mac offline'):'Live'} · ${esc(ago(data.published_at))}`;
 if(off){$('health').classList.remove('hidden');$('health').textContent=(data.mac==='stopped'?'JuneBot was closed on the Mac at ':'Mac offline — no update since ')+fmt(data.published_at)+' Arizona. It may be asleep, shut down or off the internet. Everything below is from that time.'}}
$('refreshSources').disabled=!!data.refreshing;$('refreshLabel').textContent=data.refreshing?'Checking…':'Refresh';$('versionNote').textContent='· NHL workspace v'+(data.version||'');
const recent=(data.updates||[]).filter(u=>Date.now()-new Date(u.observed_at)<6*3600e3).slice(0,6);$('updatesStrip').classList.toggle('hidden',!recent.length);$('updatesStrip').innerHTML=recent.map(u=>`<span class="chip">${u.kind==='new_team_report'?'New':'Updated'} · <strong>${esc(u.team)}</strong> · ${esc(time(u.observed_at))}</span>`).join('');
const query=$('search').value.trim().toLowerCase();const reports=valid.filter(r=>($('lineupScope').value!=='today'||teams.has(r.team))&&JSON.stringify([r.team,r.team_name,r.lines]).toLowerCase().includes(query)).sort((a,b)=>a.team_name.localeCompare(b.team_name));$('lineupCount').textContent=`${reports.length} ${reports.length===1?'team':'teams'}`;
$('lineupCards').innerHTML=reports.map(r=>`<article class="card lineup-card"><div class="team-header"><div class="team-code">${esc(r.team)}</div><div><h2>${esc(r.team_name)}</h2><p class="small">${r.lines.length} forward lines</p></div>${kindBadge(r.source?.lineup_kind)}</div>${r.lines.map(l=>`<div class="line-row"><div class="line-number">LINE ${String(l.line).padStart(2,'0')}</div><div class="players">${l.players.map(p=>{const [first,...rest]=p.name.split(' ');return `<div class="player"><span>${esc(first)}</span><strong>${esc(rest.join(' '))}</strong></div>`}).join('')}</div></div>`).join('')}<div class="card-footer"><span>Posted ${esc(r.source?.published_date||'date unknown')}${r.source?.provider?' · '+esc(r.source.provider):''}</span><a href="${esc(safeURL(r.source?.url))}" target="_blank" rel="noopener">Original report ↗</a></div></article>`).join('')||empty('No matching forward lines',$('lineupScope').value==='today'?'No complete reports yet for teams playing today. Try All teams.':'Try another team or player.');
renderGames();renderSources()}

// ------------------------------------------------------------- parlays
const STATUS={priced:'Priced',lines_not_out:'Lines not out yet',player_missing:'Player not offered',sgp_unavailable:'Won’t combine',event_not_found:'Game not listed',connection_error:'Connection problem',suspended:'Suspended',not_checked:'Not checked yet',stale:'Quote too old'};
function bookCell(name,b){const cls=b.status==='priced'?'ok':b.status==='connection_error'?'err':b.status==='not_checked'?'idle':'miss';
const main=b.status==='priced'?`<strong class="odds">${esc(am(b.odds))}</strong><small>${esc(timeS(b.observed_at))}${b.method==='relay_manual_slip'?' · your slip':''}</small>`:`<strong>${esc(STATUS[b.status]||b.status)}</strong>`;
return `<div class="book ${cls}" title="${esc(b.explanation||'')}"><span class="book-name">${esc(name)}</span>${main}${b.status!=='priced'&&b.status!=='not_checked'?`<small class="why">${esc((b.explanation||'').split(' — ').slice(1).join(' — '))}${b.inherited?' (seen in another combo, same game)':''}</small>`:''}${b.screenshot&&!PUB?`<a class="shot" href="/api/hockey/shot/${esc(b.screenshot)}" target="_blank" rel="noopener">slip ↗</a>`:''}</div>`}
function ratioBadge(r){if(r.ratio==null)return r.category==='unconfirmed'?`<span class="ratio unc">${esc(am(r.books.bet365.odds))}</span>`:'<span class="ratio none">—</span>';const c=r.category==='fire'?'fire':r.category==='qualifies'?'good':'low';return `<span class="ratio ${c}">${r.category==='fire'?'🔥 ':''}${r.ratio.toFixed(2)}×</span>`}
const LEGW={goal:'Anytime Goalscorer',assist:'To Record 1+ Assist'};
const TEAMN={ANA:'Anaheim Ducks',BOS:'Boston Bruins',BUF:'Buffalo Sabres',CGY:'Calgary Flames',CAR:'Carolina Hurricanes',CHI:'Chicago Blackhawks',COL:'Colorado Avalanche',CBJ:'Columbus Blue Jackets',DAL:'Dallas Stars',DET:'Detroit Red Wings',EDM:'Edmonton Oilers',FLA:'Florida Panthers',LAK:'Los Angeles Kings',MIN:'Minnesota Wild',MTL:'Montreal Canadiens',NSH:'Nashville Predators',NJD:'New Jersey Devils',NYI:'New York Islanders',NYR:'New York Rangers',OTT:'Ottawa Senators',PHI:'Philadelphia Flyers',PIT:'Pittsburgh Penguins',SJS:'San Jose Sharks',SEA:'Seattle Kraken',STL:'St. Louis Blues',TBL:'Tampa Bay Lightning',TOR:'Toronto Maple Leafs',UTA:'Utah Mammoth',VAN:'Vancouver Canucks',VGK:'Vegas Golden Knights',WSH:'Washington Capitals',WPG:'Winnipeg Jets'};
const takeLines=r=>r.legs.map(l=>l.kind==='team_under'?`${TEAMN[l.team]||l.team} — Team Total UNDER ${l.line} goals`:`${l.player} — ${LEGW[l.kind]}`);
const dec=a=>a>0?1+a/100:1+100/-a;
const pays=a=>'$'+Math.round(10*dec(a)).toLocaleString();
const mins=s=>{const m=Math.round(s/60);return m<60?m+' min':Math.floor(m/60)+' h '+(m%60)+' min'};
function sendCard(r){const b=r.books.bet365,f=r.books.fanduel,st=r.stats||{},s3=st.bet365;const fire=r.category==='fire';const live=r.ratio!=null&&(r.category==='fire'||r.category==='qualifies');
const unc=r.category==='unconfirmed';const cf=r.confidence||{};
const badge=live?`<span class="send-badge ${fire?'fire':'good'}">${fire?'🔥 FIRE':'✅ SEND IT'}</span>`:unc?`<span class="send-badge unc">🟡 UNCONFIRMED · bet365 only</span>`:`<span class="send-badge low">⚠️ NOT SENDABLE NOW</span>`;
const conf=cf.level?`<div class="conf conf-${esc(cf.level.toLowerCase())}" title="${esc((cf.reasons||[]).join(' · '))}"><strong>${esc(cf.level)} confidence · ${esc(cf.score)}</strong><span>${esc((cf.reasons||[]).join(' · '))}</span></div>`:'';
const next=b.observed_at?new Date(new Date(b.observed_at).getTime()+300000):null;
return `<article class="card send-card ${live?(fire?'fire':'good'):unc?'unc':'low'}"><div class="send-head">${badge}<span class="send-mult">${r.ratio!=null?r.ratio.toFixed(2)+'×':unc?esc(am(b.odds)):'—'}<small>${unc?'bet365 price · FanDuel pending':'FanDuel\'s payout'}</small></span></div>
<div class="send-game">${esc(r.event.away)} @ ${esc(r.event.home)} · ${esc(fmt(r.event.start_time))} · ${esc(r.team)} line ${esc(r.line)}${r.line===1?' <span class="depth-tag line1">⭐ LINE 1</span>':''}${r.depth?' <span class="depth-tag">LINE '+esc(r.line)+'</span>':''}${r.alerted_at?` · <span class="sent">Sent to Telegram ${esc(time(r.alerted_at))}</span>`:''}</div>
${conf}<div class="take"><div class="take-title">TAKE THIS ON BET365</div><ol>${takeLines(r).map(t=>`<li>${esc(t)}</li>`).join('')}</ol></div>
<div class="odds-row"><div class="big b365"><span>bet365</span><strong>${esc(am(b.odds))}</strong><small>${b.odds!=null?'$10 pays '+pays(b.odds):esc(STATUS[b.status]||'')}</small></div><div class="big fd"><span>FanDuel</span><strong>${esc(am(f.odds))}</strong><small>${f.odds!=null?'$10 pays '+pays(f.odds):esc(STATUS[f.status]||'')}</small></div></div>
<div class="facts"><div><span>Last checked</span><strong>${esc(time(b.observed_at))}</strong><small>${next?'next ≈ '+esc(time(next)):''}</small></div><div><span>Highest bet365</span><strong>${s3?esc(am(s3.high)):'—'}</strong><small>${s3?'at '+esc(time(s3.high_at)):''}</small></div><div><span>Steadiest bet365</span><strong>${s3?esc(am(s3.steadiest.odds)):'—'}</strong><small>${s3?'held '+esc(mins(s3.steadiest.seconds)):''}</small></div></div>
<div class="send-foot">${b.screenshot&&!PUB?`<a href="/api/hockey/shot/${esc(b.screenshot)}" target="_blank" rel="noopener"><img class="thumb" src="/api/hockey/shot/${esc(b.screenshot)}" alt="bet365 bet slip screenshot"></a>`:'<span></span>'}<button class="button" data-history="${esc(r.id)}">Price history</button></div></article>`}
function renderSendable(){const pre=r=>new Date(r.event.start_time)>Date.now();
const all=(parlays?.rows||[]).filter(pre);
const deep=all.filter(r=>r.depth&&((r.crazy&&!r.under_min)||r.alerted_at)).sort((a,b)=>(b.ratio||0)-(a.ratio||0)||(b.books.bet365.odds||0)-(a.books.bet365.odds||0));
$('depthCount').textContent=deep.length?`${deep.length} with crazy odds`:'';
$('depth').innerHTML=deep.map(sendCard).join('')||empty('Nothing crazy on lines 3–4','Lines 3–4 show here only at 3× FanDuel or more, or bet365 +25,000 and up before FanDuel posts.');
const rows=all.filter(r=>!r.depth&&r.total!==2.5&&(((r.category==='fire'||r.category==='qualifies')&&!r.under_min)||r.alerted_at));
rows.sort((a,b)=>(b.category==='fire')-(a.category==='fire')||(a.line!==1)-(b.line!==1)||(b.ratio||0)-(a.ratio||0));
$('sendable').innerHTML=rows.map(sendCard).join('')||empty('Nothing confirmed right now',`Confirmed = bet365 pays at least ${data?.rules?.minimum_payout_ratio??1.8}× FanDuel on the same four legs. JuneBot also sends these to Telegram.`);
const unc=all.filter(r=>!r.depth&&r.total!==2.5&&r.category==='unconfirmed'&&!r.under_min).sort((a,b)=>(a.line!==1)-(b.line!==1)||(b.books.bet365.odds||0)-(a.books.bet365.odds||0)).slice(0,40);
$('unconfirmedCount').textContent=unc.length?`${unc.length} parlay${unc.length===1?'':'s'} · bet365 +8,000 and up · line 1 first, then best odds`:'';
$('unconfirmed').innerHTML=unc.map(sendCard).join('')||empty('No unconfirmed parlays yet','These appear as soon as bet365 prices a combination, before FanDuel posts its lines.');
const u25=all.filter(r=>!r.depth&&r.total===2.5&&((['fire','qualifies','unconfirmed'].includes(r.category)&&!r.under_min)||r.alerted_at)).sort((a,b)=>(a.category==='unconfirmed')-(b.category==='unconfirmed')||(b.category==='fire')-(a.category==='fire')||(a.line!==1)-(b.line!==1)||(b.books.bet365.odds||0)-(a.books.bet365.odds||0)).slice(0,40);
$('u25Count').textContent=u25.length?`${u25.length} parlay${u25.length===1?'':'s'} · confirmed first, then line 1, then best odds`:'';
$('u25').innerHTML=u25.map(sendCard).join('')||empty('No Under 2.5 at +30,000 yet','Under 2.5 parlays show here only when bet365 pays +30,000 or more (confirmed or not).')}
async function showHistory(id){const r=(parlays?.rows||[]).find(x=>x.id===id);const request=++boxRequest;$('boxEyebrow').textContent='PRICE HISTORY · ACTUAL BET-SLIP QUOTES';$('boxTitle').textContent=r?takeLines(r).slice(0,3).map(t=>t.split(' — ')[0].split(' ').slice(-1)[0]).join(' / ')+` · ${r.team} U${r.total}`:'Price history';$('boxBody').textContent='Loading…';$('box').showModal();
try{const h=await get('/combo/'+id);if(request!==boxRequest)return;const st=h.stats,s3=st.bet365,sf=st.fanduel,best=st.best_ratio;
const tile=(label,val,sub)=>`<div class="hist-tile"><span>${esc(label)}</span><strong>${val}</strong><small>${sub}</small></div>`;
const rows=st.timeline.slice().reverse();
$('boxBody').innerHTML=`<div class="hist-tiles">${tile('Highest bet365',s3?esc(am(s3.high)):'—',s3?'at '+esc(time(s3.high_at)):'')}${tile('Best multiplier',best?esc(best.ratio.toFixed(2))+'×':'—',best?esc(am(best.bet365))+' vs '+esc(am(best.fanduel))+' · '+esc(time(best.at)):'')}${tile('Steadiest bet365',s3?esc(am(s3.steadiest.odds)):'—',s3?'held '+esc(mins(s3.steadiest.seconds))+' ('+esc(time(s3.steadiest.from))+'–'+esc(time(s3.steadiest.to))+')':'')}${tile('Steadiest FanDuel',sf?esc(am(sf.steadiest.odds)):'—',sf?'held '+esc(mins(sf.steadiest.seconds)):'')}</div>
<p class="small">${s3?`bet365 changed price ${s3.changes} time${s3.changes===1?'':'s'} over ${s3.checks} checks`:'No bet365 prices yet'}${sf?` · FanDuel changed ${sf.changes} time${sf.changes===1?'':'s'}`:''}. Times are Arizona.</p>
${rows.length?`<div class="table-scroll"><table><thead><tr><th>TIME</th><th>BET365</th><th>FANDUEL</th><th>MULTIPLIER</th></tr></thead><tbody>${rows.map(p=>`<tr class="${s3&&p.bet365===s3.high?'hi':''}"><td>${esc(timeS(p.at))}</td><td><strong>${esc(am(p.bet365))}</strong></td><td>${esc(am(p.fanduel))}</td><td class="${p.ratio>=3?'m-fire':p.ratio>=1.8?'m-good':'m-low'}">${esc(p.ratio.toFixed(2))}×</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">No paired prices yet.</p>'}`}catch(e){if(request===boxRequest)$('boxBody').textContent='History unavailable: '+e.message}}
function renderParlays(){if(!parlays)return;renderSendable();const rows=parlays.rows||[];const f=$('parlayFilter').value,tot=$('parlayTotal').value,q=$('parlaySearch').value.trim().toLowerCase();
const relay=data?.relay||{};const live=b=>relay[b]&&Date.now()-new Date(relay[b].last_seen)<180000;
const bannerParts=['bet365','fanduel'].map(b=>`<span class="dot ${live(b)?'on':'off'}"></span>${b==='bet365'?'bet365':'FanDuel'} relay ${live(b)?'<strong>connected</strong>'+(relay[b].state==='working'?' · pricing':''):'<strong>not connected</strong>'}`);
$('feedBanner').innerHTML=bannerParts.join('<span class="sep">·</span>')+`<span class="sep">·</span>Ratio = bet365 payout ÷ FanDuel payout. Alerts at ${esc(data?.rules?.minimum_payout_ratio??1.8)}×, 🔥 at ${esc(data?.rules?.fire_payout_ratio??3)}×.`;
let list=rows.filter(r=>(tot==='all'||String(r.total)===tot)&&(!q||JSON.stringify([r.team,r.scorer,r.assists,r.event.home,r.event.away]).toLowerCase().includes(q)));
if(f==='qualifying')list=list.filter(r=>r.category==='fire'||r.category==='qualifies');
if(f==='priced')list=list.filter(r=>r.ratio!=null);
if(f==='unconfirmed')list=list.filter(r=>r.category==='unconfirmed');
if(f==='top')list=list.filter(r=>!r.depth);if(f==='depth')list=list.filter(r=>r.depth);
if(f==='unavailable')list=list.filter(r=>['bet365','fanduel'].some(b=>!['priced','not_checked','stale'].includes(r.books[b].status)));
$('parlayCount').textContent=`${list.length} of ${rows.length} combinations`;
if(!list.length){$('parlayList').innerHTML=f==='qualifying'?empty('Nothing qualifies right now',rows.length?`${data?.counts?.priced_both||0} of ${rows.length} combinations have prices from both books so far. Switch to “All combinations” to see what is missing and why.`:'No pregame combinations yet — they appear once forward lines are posted for upcoming games.'):empty('No combinations in this view','Try another filter.');return}
const groups=new Map();for(const r of list){const k=r.event.id+'|'+r.team+'|'+r.line;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}
$('parlayList').innerHTML=[...groups.values()].map(g=>{const r0=g[0];const trio=[r0.scorer,...r0.assists];return `<article class="card parlay-group"><div class="pg-head"><div class="team-code">${esc(r0.team)}</div><div><h2>${esc(r0.event.away)} @ ${esc(r0.event.home)} <small>${esc(fmt(r0.event.start_time))}</small></h2><p class="small">${esc(r0.team)} line ${esc(r0.line)} · ${trio.map(esc).join(' · ')} ${r0.source?.lineup_kind&&r0.source.lineup_kind!=='reported'?'· '+esc(r0.source.lineup_kind):''}</p></div></div>${g.map(r=>`<div class="combo ${r.category}"><div class="combo-legs"><div><span class="leg-tag goal">G</span>${esc(r.scorer)}</div><div><span class="leg-tag ast">A</span>${esc(r.assists[0])}</div><div><span class="leg-tag ast">A</span>${esc(r.assists[1])}</div><div><span class="leg-tag tot">U</span>${esc(r.team)} under ${esc(r.total)}</div></div>${bookCell('bet365',r.books.bet365)}${bookCell('FanDuel',r.books.fanduel)}<div class="combo-side">${ratioBadge(r)}${r.confidence?`<small class="conf-chip conf-${esc(r.confidence.level.toLowerCase())}">${esc(r.confidence.level)} conf.</small>`:''}${r.note?`<small>${esc(r.note)}</small>`:''}<div class="combo-actions"><button class="mini" data-history="${esc(r.id)}">History</button><button class="mini owner-only" data-recheck="${esc(r.id)}">Recheck</button><button class="mini owner-only" data-track="${esc(r.id)}">Track</button></div></div></div>`).join('')}</article>`}).join('')}

// ------------------------------------------------------------- games
function renderGames(){if(!data)return;const today=azDate(Date.now());const mode=$('gameFilter').value;const now=Date.now();
const reports=new Map(data.reports.filter(usable).map(r=>[r.team,r]));
const games=data.games.filter(g=>mode==='all'||mode==='today'&&azDate(g.start_time)===today||mode==='upcoming'&&['FUT','PRE'].includes(g.state)&&new Date(g.start_time)>now-3600e3||mode==='live'&&['LIVE','CRIT'].includes(g.state)||mode==='final'&&['OFF','FINAL'].includes(g.state));
const list=mode==='upcoming'?games.slice(0,40):games;$('gameCount').textContent=`${list.length} ${list.length===1?'game':'games'}`;
const lineChip=t=>{const r=reports.get(t);return r?`<span class="chip ok">${esc(t)} lines · ${esc(r.source?.lineup_kind==='projected'?'projected':r.source?.lineup_kind||'reported')}</span>`:`<span class="chip">${esc(t)} lines pending</span>`};
$('gameCards').innerHTML=list.map(g=>`<article class="card game-card"><div class="meta"><span>${esc(fmt(g.start_time))}</span><span class="badge">${esc(stateName(g.state))}</span></div><div class="match">${esc(g.away)} <small>AT</small> ${esc(g.home)}</div><div class="meta"><span>${g.away_score==null||g.home_score==null?'Score pending':`${Number(g.away_score)} — ${Number(g.home_score)}`}</span><span>Arizona time</span></div>${['FUT','PRE'].includes(g.state)?`<div class="chips">${lineChip(g.away)}${lineChip(g.home)}</div>`:''}<button class="button" data-game="${esc(g.id)}" aria-label="Box score for ${esc(g.away)} at ${esc(g.home)}">View box score ↗</button></article>`).join('')||empty('No games in this view','Choose another schedule filter.')}

// ------------------------------------------------------------- results
const LEG_ICON={reached:'✓',under_final:'✓',under_so_far:'…',pending:'…',over_limit:'✕',not_reached_final:'✕',unknown:'?'};
async function renderResults(){const box=$('resultList');try{const r=await get('/results');const f=$('resultFilter').value;let w=r.watched||[];
w=w.filter(x=>f==='all'||(f==='done'?['stats_met','stats_not_met','needs_review'].includes(x.progress.status):!['stats_met','stats_not_met','needs_review'].includes(x.progress.status)));
$('resultCount').textContent=`${w.length} tracked`;
box.innerHTML=w.map(x=>{const c=x.candidate,p=x.progress;const st={pregame:'Pregame',live:'Live',live_partial_data:'Live',stats_met:'All legs hit',stats_not_met:'Missed',needs_review:'Needs review',awaiting_game_data:'Waiting'}[p.status]||p.status;
const legs=(p.legs&&p.legs.length?p.legs:c.legs.map(l=>({label:l.market==='team_total_goals'?`${c.team} Under ${l.line} goals`:`${l.player_id.split('_').slice(0,-2).join(' ')} 1+ ${l.market==='player_goals'?'goals':'assists'}`,status:'pending',value:null})));
return `<article class="card result ${esc(p.status)}"><div class="pg-head"><div class="team-code">${esc(c.team)}</div><div><h2>${esc(c.event.away)} @ ${esc(c.event.home)} <small>${esc(fmt(c.event.start_time))}</small></h2><p class="small">${esc(p.score||'')} ${x.accepted_odds?'· bet365 '+esc(am(x.accepted_odds))+' when alerted':''}</p></div><span class="badge ${p.status==='stats_met'?'':'muted-badge'}">${esc(st)}</span></div><ul class="legs">${legs.map(l=>`<li class="leg ${esc(l.status)}"><span>${LEG_ICON[l.status]||'…'}</span>${esc(l.label)}${l.value!=null?` <small>(${esc(l.value)})</small>`:''}</li>`).join('')}</ul><div class="card-footer"><span>${esc(p.note||'Official full-game statistics; not sportsbook settlement.')}</span><button class="mini owner-only" data-untrack="${esc(x.id)}">Remove</button></div></article>`}).join('')||empty('Nothing tracked yet','Alerted combinations are tracked automatically; you can also press Track on any parlay.')}catch(e){box.innerHTML=empty('Results unavailable',e.message)}}

// ------------------------------------------------------------- history
async function renderHistory(){try{const h=await get('/history');
$('scanList').innerHTML=h.scans.slice(0,120).map(s=>`<div class="log ${esc(s.kind)}"><time>${esc(fmt(s.at))}</time><span>${esc(s.summary)}</span></div>`).join('')||'<p class="small">No scans yet.</p>';
$('updateList').innerHTML=h.updates.map(u=>`<div class="log"><time>${esc(fmt(u.observed_at))}</time><span><strong>${esc(u.team)}</strong> ${u.kind==='new_team_report'?'new report':'updated report'} · ${esc(u.line_count)} lines ${u.source?.url?`· <a href="${esc(safeURL(u.source.url))}" target="_blank" rel="noopener">source ↗</a>`:''}</span></div>`).join('')||'<p class="small">No changes recorded since JuneBot started.</p>';
$('quoteList').innerHTML=h.quotes.map(q=>`<div class="log ${q.status==='priced'?'ok':q.status==='connection_error'?'error':''}"><time>${esc(timeS(q.received_at))}</time><span><strong>${esc(q.book==='bet365'?'bet365':'FanDuel')}</strong> · ${esc(STATUS[q.status]||q.status)}${q.american_odds!=null?' '+esc(am(q.american_odds)):''}${q.missing?.length?' — '+esc(q.missing.map(m=>(m.player||m.team||'')+' '+m.reason).join('; ')):''}${q.detail&&q.status!=='priced'?' · '+esc(q.detail):''}</span></div>`).join('')||'<p class="small">No sportsbook checks yet. Connect the Quote Relay (Status page).</p>';
$('alertList').innerHTML=h.alerts.map(a=>`<div class="log ${a.delivered?'ok':'error'}"><time>${esc(fmt(a.sent_at))}</time><span>${a.category==='fire'?'🔥 ':''}${esc(a.ratio?.toFixed?.(2))}× · bet365 ${esc(am(a.bet365))} / FD ${esc(am(a.fanduel))} ${a.delivered?'':'· not delivered: '+esc(a.error)}<details><summary>Message</summary><pre>${esc((a.message||'').replace(/<[^>]+>/g,''))}</pre></details></span></div>`).join('')||'<p class="small">No alerts sent yet.</p>'}catch(e){$('scanList').innerHTML=empty('History unavailable',e.message)}}

// ------------------------------------------------------------- sources
function srcCard(title,badge,cls,body,extra){return `<article class="card source-card"><span class="badge ${cls}">${esc(badge)}</span><h2>${esc(title)}</h2><p>${body}</p>${extra||''}</article>`}
function renderSources(){if(!data)return;const s=data.sources||{},relay=data.relay||{},tg=data.telegram||{};
const src=(k,title,desc)=>{const x=s[k];return srcCard(title,!x?'NOT CHECKED':x.ok?'CONNECTED':'CHECK NEEDED',!x?'muted-badge':x.ok?'':'warn-badge',desc,`<div class="source-note">${x?esc((x.ok?'':'Problem: ')+x.detail)+' · '+esc(ago(x.at)):'Waiting for the first check.'}</div>`)};
const rel=b=>{const r=relay[b];const live=r&&Date.now()-new Date(r.last_seen)<180000;const name=b==='bet365'?'bet365':'FanDuel';
return srcCard(name+' bet slip (Quote Relay)',live?(r.state==='error'?'RELAY ERROR':'CONNECTED'):'NOT CONNECTED',live?(r.state==='error'?'warn-badge':''):'muted-badge',`Actual combined ${name} prices read from your own bet slip in Chrome (Arizona).`,`<div class="source-note">${r?`Last seen ${esc(ago(r.last_seen))}${r.signed_in===false?' · appears signed out':''}${r.note?' · '+esc(r.note):''}`:'Install the extension and turn on Auto-price.'}</div>`)};
const macCard=PUB?(()=>{const age=pubAge(),off=data.mac==='stopped'||age>5;return srcCard('JuneBot Mac',off?(data.mac==='stopped'?'STOPPED':'OFFLINE'):'ONLINE',off?'warn-badge':'',off?(data.mac==='stopped'?'JuneBot was closed on the Mac.':'No updates from the Mac. It may be asleep, shut down or off the internet.'):'The Mac is running JuneBot and updating this board every minute.',`<div class="source-note">Last update ${esc(fmt(data.published_at))} Arizona · ${esc(ago(data.published_at))}</div>`)})():'';
$('sourceGrid').innerHTML=macCard+src('gamedaytweets','GameDayTweets lines','Primary forward-line source. Checked every 5 minutes, every 2 minutes when a game starts within 3 hours.')+src('nhl_schedule','Official NHL schedule','Games, start times, scores and box scores.')+src('dailyfaceoff','Daily Faceoff (backup)','Projected lines for teams playing within 12 hours without a GameDayTweets report.')+rel('bet365')+rel('fanduel')+src('fanduel_api','FanDuel market check','Confirms posted markets so “lines not out yet” is shown only when FanDuel confirms it. Not a price source.')+(PUB?'':srcCard('Telegram',tg.configured?(data.settings?.alerts_enabled?'ON':'PAUSED'):'NOT CONFIGURED',tg.configured&&data.settings?.alerts_enabled?'':'muted-badge','Qualifying combinations, fully written out with both books’ prices and check times; bet365 slip screenshot when available.',`<div class="source-note">${tg.last_sent?'Last alert '+esc(ago(tg.last_sent)):'No alerts sent yet'}${tg.last_error?' · Last error: '+esc(tg.last_error):''}</div>`));
$('setAlerts').checked=!!data.settings?.alerts_enabled;$('setFdApi').checked=!!data.settings?.fanduel_api;$('setDf').checked=!!data.settings?.dailyfaceoff;
const pub=data.public||{};$('publicState').innerHTML=pub.url?`<strong>Link:</strong> <a href="${esc(safeURL(pub.url))}" target="_blank" rel="noopener">${esc(pub.url)}</a><br>${pub.error?'<span style="color:var(--warn)">Last push failed: '+esc(pub.error)+'</span>':pub.last_push?'Last updated '+esc(ago(pub.last_push)):'Publishing…'}`:(pub.connected?(pub.error?'<span style="color:var(--warn)">'+esc(pub.error)+'</span>':'Setting up the page…'):'Not connected yet.');$('publicConnect').classList.toggle('hidden',!!pub.connected&&!pub.error);
const r=data.rules||{};$('rulesNote').textContent=`Rules: alert at ${r.minimum_payout_ratio}× FanDuel's payout, 🔥 Fire at ${r.fire_payout_ratio}×, +${(r.preferred_american_odds||10000).toLocaleString()} is a preference only. Both quotes must be under ${r.alert_max_quote_age_seconds}s old and within ${r.alert_max_quote_skew_seconds}s of each other; JuneBot rechecks both books automatically before alerting.`}

// ------------------------------------------------------------- data loading
async function refresh(){try{data=await get('');renderTop();if(page()==='parlays')await loadParlays();if(data.refreshing){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,2000)}}catch(e){$('health').textContent=PUB?'Live data is unavailable right now — retrying every minute.':'JuneBot is disconnected from its local server. Reopen Open JuneBot.command to reconnect.';$('health').classList.remove('hidden');$('refreshSources').disabled=false}}
async function loadParlays(){try{parlays=await get('/parlays');renderParlays()}catch(e){$('parlayList').innerHTML=empty('Parlays unavailable',e.message)}}
function loadPage(){const p=page();if(p==='parlays')loadParlays();if(p==='results')renderResults();if(p==='history')renderHistory()}
$('search').oninput=renderTop;$('lineupScope').onchange=renderTop;$('gameFilter').onchange=renderGames;$('resultFilter').onchange=renderResults;
['parlayFilter','parlayTotal'].forEach(id=>$(id).onchange=renderParlays);$('parlaySearch').oninput=renderParlays;
$('refreshSources').onclick=async()=>{try{$('refreshSources').disabled=true;$('refreshLabel').textContent='Checking…';await post('/refresh');await refresh()}catch(e){$('health').textContent=e.message;$('health').classList.remove('hidden');$('refreshSources').disabled=false;$('refreshLabel').textContent='Refresh'}};
$('showKey').onclick=async()=>{try{const r=await post('/relay-key');$('relayKey').textContent=r.relay_key;$('relayKey').classList.remove('hidden')}catch(e){$('relayKey').textContent=e.message;$('relayKey').classList.remove('hidden')}};
$('ghSave').onclick=async()=>{$('ghMsg').textContent='Connecting…';try{await post('/github-token',{token:$('ghToken').value});$('ghToken').value='';$('ghMsg').textContent='Connected — the link appears here in about a minute.';setTimeout(refresh,8000)}catch(e){$('ghMsg').textContent=e.message}};
$('tgTest').onclick=async()=>{$('tgMsg').textContent='Sending…';try{await post('/telegram-test');$('tgMsg').textContent='Sent. Check Telegram.'}catch(e){$('tgMsg').textContent=e.message}};
for(const [id,key] of [['setAlerts','alerts_enabled'],['setFdApi','fanduel_api'],['setDf','dailyfaceoff']])$(id).onchange=async e=>{try{await post('/settings',{[key]:e.target.checked});await refresh()}catch(err){alert(err.message)}};
$('closeBox').onclick=()=>$('box').close();
document.addEventListener('click',async e=>{
 const hb=e.target.closest('[data-history]');if(hb){showHistory(hb.dataset.history);return}
 const t=e.target.closest('[data-track],[data-untrack],[data-recheck]');
 if(t){try{if(t.dataset.track){await post('/track',{candidate_id:t.dataset.track});t.textContent='Tracked ✓'}if(t.dataset.untrack){await post('/untrack',{candidate_id:t.dataset.untrack});renderResults()}if(t.dataset.recheck){await post('/recheck',{candidate_id:t.dataset.recheck});t.textContent='Queued ✓'}}catch(err){t.textContent=err.message.slice(0,40)}return}
 const b=e.target.closest('[data-game]');if(!b)return;const g=data.games.find(x=>x.id===b.dataset.game);if(!g)return;const request=++boxRequest;$('boxEyebrow').textContent='OFFICIAL NHL BOX SCORE';$('boxTitle').textContent=`${g.away} at ${g.home}`;$('boxBody').textContent='Loading official statistics…';$('box').showModal();
 try{const score=await get('/boxscore/'+g.id);if(request!==boxRequest)return;$('boxBody').innerHTML=`<p class="small">${esc(stateName(score.state))} · Checked ${esc(fmt(score.observed_at))} Arizona</p>${score.teams.map(t=>`<div class="box-team"><h2>${esc(t.team)} <span class="badge">${t.score==null?'Score pending':Number(t.score)+' goals'}</span></h2>${t.skaters.length?`<div class="table-scroll"><table><thead><tr><th>PLAYER</th><th>GOALS</th><th>ASSISTS</th><th>SHOTS</th><th>ICE TIME</th></tr></thead><tbody>${t.skaters.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.goals??'—')}</td><td>${esc(p.assists??'—')}</td><td>${esc(p.shots??'—')}</td><td>${esc(p.time_on_ice??'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">Player statistics have not been posted yet.</p>'}</div>`).join('')}<p class="small" style="margin-top:24px">${esc(score.note)}</p>`}catch(err){if(request===boxRequest)$('boxBody').textContent='Box score unavailable: '+err.message}});
try{$('motionToggle').checked=localStorage.getItem('junebot-motion')!=='off'}catch{}function motion(){document.body.classList.toggle('motion-off',!$('motionToggle').checked)}motion();$('motionToggle').onchange=()=>{motion();try{localStorage.setItem('junebot-motion',$('motionToggle').checked?'on':'off')}catch{}};
try{const saved=localStorage.getItem('junebot-scope');if(saved)$('lineupScope').value=saved;$('lineupScope').addEventListener('change',()=>{try{localStorage.setItem('junebot-scope',$('lineupScope').value)}catch{}})}catch{}
showPage();if(PUB&&PUBDATA){data=Object.assign({},PUBDATA.hockey,{published_at:PUBDATA.published_at,mac:PUBDATA.mac});renderTop();loadPage()}refresh();setInterval(()=>{if(!document.hidden){refresh();const p=page();if(p==='results')renderResults();if(p==='history')renderHistory()}},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
