'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return u.protocol==='https:'?u.href:'#'}catch{return '#'}};
const AZ={timeZone:'America/Phoenix'};
const fmt=s=>s?new Date(s).toLocaleString('en-US',{...AZ,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not available';
const time=s=>s?new Date(s).toLocaleTimeString('en-US',{...AZ,hour:'numeric',minute:'2-digit'}):'—';
const timeS=s=>s?new Date(s).toLocaleTimeString('en-US',{...AZ,hour:'numeric',minute:'2-digit',second:'2-digit'}):'—';
const azDate=s=>new Date(s).toLocaleDateString('en-CA',AZ);
const ago=s=>{if(!s)return '';const m=Math.round((Date.now()-new Date(s))/60000);return m<1?'just now':m<60?m+' min ago':Math.round(m/60)+' h ago'};
const am=v=>v==null?'—':(v>0?'+':'')+Math.round(v);
const stateName=s=>({FUT:'Upcoming',PRE:'Pregame',LIVE:'In progress',CRIT:'In progress',OFF:'Final',FINAL:'Final'})[s]||s||'Unknown';
const empty=(title,note)=>`<div class="empty"><strong>${esc(title)}</strong>${esc(note)}</div>`;
const token=()=>document.querySelector('meta[name=refresh-token]').content;
let data=null,parlays=null,boxRequest=0,refreshTimer=null;
const pageInfo={lineups:['Every line, in focus.','Complete forward-line reports, organized by team.','Lines'],
  parlays:['Parlays worth a look.','Anytime goal + two linemate assists + own-team under — real bet365 & FanDuel prices.','Parlays'],
  games:['The game starts here.','Upcoming games, lineup status, scores and box scores.','Upcoming'],
  results:['How they played out.','Tracked combinations, leg by leg, from official NHL statistics.','Results'],
  history:['What JuneBot checked.','Lineup scans, report changes, sportsbook checks and alerts.','History'],
  sources:['A clear view of the data.','What is connected, what is not, and when it was last checked.','Status']};
function page(){const id=location.hash.slice(1);return pageInfo[id]?id:'parlays'}
function showPage(){const id=location.hash.slice(1);if(id==='main')return;const p=page();document.querySelectorAll('[data-page]').forEach(a=>{if(a.dataset.page===p)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});Object.keys(pageInfo).forEach(k=>$(k+'Page').classList.toggle('hidden',k!==p));$('pageTitle').textContent=pageInfo[p][0];$('pageSubtitle').textContent=pageInfo[p][1];document.title='JuneBot · '+pageInfo[p][2];window.scrollTo({top:0,behavior:'auto'});loadPage()}
window.addEventListener('hashchange',showPage);
// ---- Public read-only mode (the GitHub-hosted copy): same UI, data comes from JuneBot's published snapshot.
const PUB=window.JUNEBOT_PUBLIC||null;let PUBDATA=null,pubAt=0,pubLoading=null;
if(PUB){document.body.classList.add('public');try{PUBDATA=JSON.parse(localStorage.getItem('jb-pub')||'null')}catch{}}
async function pubFetch(){
 try{const r=await fetch('https://api.github.com/gists/'+PUB.gist,{cache:'no-store'});if(!r.ok)throw Error('api '+r.status);const g=await r.json();const f=g.files['data.json'];
  const c=f.truncated?await (await fetch(f.raw_url,{cache:'no-store'})).text():f.content;return JSON.parse(c)}
 catch(e){const r=await fetch(`https://gist.githubusercontent.com/${PUB.login}/${PUB.gist}/raw/data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Live data unavailable');return JSON.parse(await r.text())}}
async function pubLoad(){if(PUBDATA&&Date.now()-pubAt<50000)return PUBDATA;if(!pubLoading)pubLoading=pubFetch().then(d=>{PUBDATA=d;pubAt=Date.now();try{localStorage.setItem('jb-pub',JSON.stringify(d))}catch{}return d}).finally(()=>{pubLoading=null});
 try{return await pubLoading}catch(e){if(PUBDATA)return PUBDATA;throw e}}
function pubAge(){return PUBDATA&&PUBDATA.published_at?(Date.now()-new Date(PUBDATA.published_at))/60000:Infinity}
async function pubGet(path){const d=(PUBDATA&&!pubAt)?(pubLoad(),PUBDATA):await pubLoad();
 if(path==='')return Object.assign({},d.hockey,{published_at:d.published_at,mac:d.mac});
 if(path==='/parlays')return d.parlays;if(path==='/history')return d.history;if(path==='/results')return d.results;
 if(path.startsWith('/combo/')){const r=(d.parlays.rows||[]).find(x=>x.id===path.split('/').pop());return{quotes:[],stats:(r&&r.stats)||{timeline:[]}}}
 if(path.startsWith('/boxscore/')){const b=(d.boxscores||{})[path.split('/').pop()];if(!b)throw Error('Box score not published yet for this game');return b}
 throw Error('Not available on the public board')}
async function get(path){if(PUB)return pubGet(path);const r=await fetch('/api/hockey'+path,{cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'Data unavailable');return body}
async function post(path,body){const r=await fetch('/api/hockey'+path,{method:'POST',headers:{'X-Refresh-Token':token(),'Content-Type':'application/json'},body:JSON.stringify(body||{})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b}
function usable(r){const lines=r.lines||[];return !r.review_reasons?.length&&lines.length>=1&&lines.length<=4&&lines.every(l=>l.players.length===3&&l.players.every(p=>['C','L','R','LW','RW','F'].includes(p.position)&&p.team===r.team))}
const kindBadge=k=>k==='practice'?'<span class="badge practice">PRACTICE</span>':k==='projected'?'<span class="badge practice">PROJECTED · DAILY FACEOFF</span>':'<span class="badge">REPORTED</span>';

// ------------------------------------------------------------- header + lines
function renderTop(){if(!data)return;linesToast();const today=azDate(Date.now());const todays=data.games.filter(g=>azDate(g.start_time)===today);const teams=new Set(todays.flatMap(g=>[g.home,g.away]));const valid=data.reports.filter(usable);const c=data.counts||{};
$('reportCount').textContent=valid.length;$('comboCount').textContent=c.combinations??'—';$('comboNote').textContent=c.priced_both!=null?`${c.priced_both} priced at both books`:'6 per forward line';
$('qualCount').textContent=c.qualifying!=null?(c.qualifying+(c.unconfirmed||0)):'—';$('qualNote').textContent=`${c.qualifying||0} confirmed${c.fire?' ('+c.fire+' 🔥)':''} · ${c.unconfirmed||0} unconfirmed`;
$('checkTime').textContent=time(data.updated_at);const stale=!data.updated_at||Date.now()-new Date(data.updated_at).getTime()>420000;$('freshness').textContent=stale?'Waiting for a fresh scan':'Checks every 2–5 minutes';
$('health').classList.toggle('hidden',!data.error&&!stale);$('health').textContent=data.error?'Source refresh failed. Showing the last available data. '+data.error:!data.updated_at?'Waiting for the first source check.':'The source snapshot is older than seven minutes. Refresh to check for updates.';
if(PUB){const age=pubAge(),off=data.mac==='stopped'||age>5;const pill=$('livePill');pill.classList.remove('hidden');pill.className='live-pill '+(off?'off':'on');
 pill.innerHTML=`<span class="dot ${off?'off':'on'}"></span>${off?(data.mac==='stopped'?'JuneBot stopped':'Mac offline'):'Live'} · ${esc(ago(data.published_at))}`;
 if(off){$('health').classList.remove('hidden');$('health').textContent=(data.mac==='stopped'?'JuneBot was closed on the Mac at ':'Mac offline — no update since ')+fmt(data.published_at)+' Arizona. It may be asleep, shut down or off the internet. Everything below is from that time.'}}
$('refreshSources').disabled=!!data.refreshing;$('refreshLabel').textContent=data.refreshing?'Checking…':'Refresh';$('versionNote').textContent='· NHL workspace v'+(data.version||'');
const recent=(data.updates||[]).filter(u=>Date.now()-new Date(u.observed_at)<6*3600e3).slice(0,6);$('updatesStrip').classList.toggle('hidden',!recent.length);$('updatesStrip').innerHTML=recent.map(u=>`<span class="chip">${u.kind==='new_team_report'?'New':'Updated'} · <strong>${esc(u.team)}</strong> · ${esc(time(u.observed_at))}</span>`).join('');
const query=$('search').value.trim().toLowerCase();const reports=valid.filter(r=>($('lineupScope').value!=='today'||teams.has(r.team))&&JSON.stringify([r.team,r.team_name,r.lines]).toLowerCase().includes(query)).sort((a,b)=>a.team_name.localeCompare(b.team_name));$('lineupCount').textContent=`${reports.length} ${reports.length===1?'team':'teams'}`;
$('lineupCards').innerHTML=reports.map(r=>`<article class="card lineup-card"><div class="team-header"><div class="team-code">${esc(r.team)}</div><div><h2>${esc(r.team_name)}</h2><p class="small">${r.lines.length} forward lines</p></div>${kindBadge(r.source?.lineup_kind)}</div>${r.lines.map(l=>`<div class="line-row"><div class="line-number">LINE ${String(l.line).padStart(2,'0')}</div><div class="players">${l.players.map(p=>{const [first,...rest]=p.name.split(' ');return `<div class="player"><span>${esc(first)}</span><strong>${esc(rest.join(' '))}</strong></div>`}).join('')}</div></div>`).join('')}<div class="card-footer"><span>Posted ${esc(r.source?.published_date||'date unknown')}${r.source?.provider?' · '+esc(r.source.provider):''}</span><a href="${esc(safeURL(r.source?.url))}" target="_blank" rel="noopener">Original report ↗</a></div></article>`).join('')||empty('No matching forward lines',$('lineupScope').value==='today'?'No complete reports yet for teams playing today. Try All teams.':'Try another team or player.');
renderGames();renderSources()}

// ------------------------------------------------------------- parlays
const STATUS={priced:'Priced',lines_not_out:'Lines not out yet',player_missing:'Player not offered',sgp_unavailable:'Won’t combine',event_not_found:'Game not listed',connection_error:'Connection problem',suspended:'Suspended',not_checked:'Not checked yet',stale:'Quote too old'};
function bookCell(name,b){const cls=b.status==='priced'?'ok':b.status==='connection_error'?'err':b.status==='not_checked'?'idle':'miss';
const main=b.status==='priced'?`<strong class="odds">${esc(am(b.odds))}</strong><small>${esc(timeS(b.observed_at))}${b.method==='relay_manual_slip'?' · your slip':''}</small>`:`<strong>${esc(STATUS[b.status]||b.status)}</strong>`;
return `<div class="book ${cls}" title="${esc(b.explanation||'')}"><span class="book-name">${esc(name)}</span>${main}${b.status!=='priced'&&b.status!=='not_checked'?`<small class="why">${esc((b.explanation||'').split(' — ').slice(1).join(' — '))}${b.inherited?' (seen in another combo, same game)':''}</small>`:''}${b.screenshot&&!PUB?`<a class="shot" href="/api/hockey/shot/${esc(b.screenshot)}" target="_blank" rel="noopener">slip ↗</a>`:''}</div>`}
function ratioBadge(r){if(r.ratio==null)return r.category==='unconfirmed'?`<span class="ratio unc">${esc(am(r.books.bet365.odds))}</span>`:'<span class="ratio none">—</span>';const c=r.category==='fire'?'fire':r.category==='qualifies'?'good':'low';return `<span class="ratio ${c}">${r.category==='fire'?'🔥 ':''}${r.ratio.toFixed(2)}×</span>`}
const LEGW={goal:'Anytime Goalscorer',assist:'To Record 1+ Assist'};
const TEAMN={ANA:'Anaheim Ducks',BOS:'Boston Bruins',BUF:'Buffalo Sabres',CGY:'Calgary Flames',CAR:'Carolina Hurricanes',CHI:'Chicago Blackhawks',COL:'Colorado Avalanche',CBJ:'Columbus Blue Jackets',DAL:'Dallas Stars',DET:'Detroit Red Wings',EDM:'Edmonton Oilers',FLA:'Florida Panthers',LAK:'Los Angeles Kings',MIN:'Minnesota Wild',MTL:'Montreal Canadiens',NSH:'Nashville Predators',NJD:'New Jersey Devils',NYI:'New York Islanders',NYR:'New York Rangers',OTT:'Ottawa Senators',PHI:'Philadelphia Flyers',PIT:'Pittsburgh Penguins',SJS:'San Jose Sharks',SEA:'Seattle Kraken',STL:'St. Louis Blues',TBL:'Tampa Bay Lightning',TOR:'Toronto Maple Leafs',UTA:'Utah Mammoth',VAN:'Vancouver Canucks',VGK:'Vegas Golden Knights',WSH:'Washington Capitals',WPG:'Winnipeg Jets'};
const takeLines=r=>r.legs.map(l=>l.kind==='team_under'?`${TEAMN[l.team]||l.team} — Team Total UNDER ${l.line} goals`:`${l.player} — ${LEGW[l.kind]}`);
const dec=a=>a>0?1+a/100:1+100/-a;
const pays=a=>'$'+Math.round(10*dec(a)).toLocaleString();
const mins=s=>{const m=Math.round(s/60);return m<60?m+' min':Math.floor(m/60)+' h '+(m%60)+' min'};
// Older prices stay on the board, clearly marked, while JuneBot keeps re-pricing them.
function staleNote(b){if(!b||!b.observed_at)return '';const m=Math.floor((Date.now()-new Date(b.observed_at).getTime())/60000);if(m<30)return '';
const t=m>=120?Math.floor(m/60)+' h '+(m%60)+' min':m+' min';return `<div class="stale-note">⏳ Not updated in ${esc(t)} · last bet365 price shown · JuneBot is re-checking it</div>`}
// ------------------------------------------------------------- the board (tickets)
const BOARD_TABS=[['top','⭐ Top picks'],['confirmed','✅ Confirmed'],['u35','Under 3.5'],['u25','💎 Under 2.5 · 30k+'],['deep','Lines 3–4']];
let boardTab='top',boardGame='all';const openTickets=new Set();try{boardTab=localStorage.getItem('jb-tab')||'top';$('boardSort').value=localStorage.getItem('jb-sort')||'smart'}catch{}
const isConf=r=>r.ratio!=null&&(r.category==='fire'||r.category==='qualifies');
const onBoard=r=>new Date(r.event.start_time)>Date.now()&&(((isConf(r)||r.category==='unconfirmed')&&!r.under_min&&(!r.depth||r.crazy))||r.alerted_at);
function boardSets(rows){const b=rows.filter(onBoard);return{top:b,confirmed:b.filter(isConf),u35:b.filter(r=>!r.depth&&r.total!==2.5),u25:b.filter(r=>!r.depth&&r.total===2.5),deep:b.filter(r=>r.depth)}}
const gameKey=r=>r.event.id;const gameLabel=r=>`${r.event.away} @ ${r.event.home}`;
function sortBoard(list){const mode=$('boardSort').value;const odds=r=>r.books.bet365.odds||0;const cat=r=>r.category==='fire'?0:r.category==='qualifies'?1:2;
 return list.slice().sort(mode==='odds'?(a,b)=>odds(b)-odds(a):mode==='time'?(a,b)=>new Date(a.event.start_time)-new Date(b.event.start_time)||(a.line!==1)-(b.line!==1)||odds(b)-odds(a):(a,b)=>cat(a)-cat(b)||(a.line!==1)-(b.line!==1)||odds(b)-odds(a))}
const dayTime=s=>{const d=new Date(s),t=new Date();const same=d.toLocaleDateString('en-CA',AZ)===t.toLocaleDateString('en-CA',AZ);const tm=new Date(t.getTime()+864e5);const tom=d.toLocaleDateString('en-CA',AZ)===tm.toLocaleDateString('en-CA',AZ);
 return (same?'Today ':tom?'Tomorrow ':d.toLocaleDateString('en-US',{...AZ,weekday:'short'})+' ')+time(s)};
function ticket(r){const b=r.books.bet365,f=r.books.fanduel,st=r.stats||{},s3=st.bet365,cf=r.confidence||{};const conf=isConf(r),fire=r.category==='fire';
 const state=fire?'<span class="tag t-fire">🔥 FIRE</span>':conf?'<span class="tag t-good">✅ CONFIRMED</span>':'<span class="tag t-unc">🟡 UNCONFIRMED</span>';
 const legs=r.legs.map(l=>l.kind==='team_under'?`<li><span class="lg u">U</span><b>${esc(TEAMN[l.team]||l.team)}</b><em>Under ${esc(l.line)} goals</em></li>`:`<li><span class="lg ${l.kind==='goal'?'g':'a'}">${l.kind==='goal'?'G':'A'}</span><b>${esc(l.player)}</b><em>${l.kind==='goal'?'Anytime goal':'1+ assist'}</em></li>`).join('');
 const fd=f.odds!=null?`<b>${esc(am(f.odds))}</b><small>${esc(ago(f.observed_at))}</small>`:`<b class="muted">—</b><small>${esc(STATUS[f.status]||f.status)}</small>`;
 const next=b.observed_at?new Date(new Date(b.observed_at).getTime()+600000):null;
 return `<article class="ticket ${fire?'fire':conf?'good':'unc'}" data-id="${esc(r.id)}">
<div class="t-top"><div class="t-tags">${r.line===1?'<span class="tag t-l1">⭐ LINE 1</span>':`<span class="tag">LINE ${esc(r.line)}</span>`}<span class="tag t-tot">U${esc(r.total)}</span>${state}${r.alerted_at?'<span class="tag t-sent">SENT</span>':''}</div>
<div class="t-odds">${esc(am(b.odds))}<small>$10 → ${b.odds!=null?pays(b.odds):'—'}</small></div></div>
<div class="t-game">${esc(gameLabel(r))} · ${esc(dayTime(r.event.start_time))} · ${esc(r.team)}${r.source?.lineup_kind&&r.source.lineup_kind!=='reported'?' · '+esc(r.source.lineup_kind)+' lines':''}</div>
<ol class="t-legs">${legs}</ol>${staleNote(b)}
<div class="t-books"><div class="tb b365"><span>bet365</span><b>${esc(am(b.odds))}</b><small>checked ${esc(ago(b.observed_at))}</small></div><div class="tb fd"><span>FanDuel</span>${fd}</div>${r.ratio!=null?`<div class="tb mult ${fire?'fire':conf?'good':'low'}"><span>vs FanDuel</span><b>${esc(r.ratio.toFixed(2))}×</b><small>payout</small></div>`:''}</div>
<div class="t-foot"><span class="conf-chip conf-${esc((cf.level||'low').toLowerCase())}" title="${esc((cf.reasons||[]).join(' · '))}">${esc(cf.level||'—')} confidence</span><button class="mini t-more-btn" data-expand="${esc(r.id)}" aria-expanded="${openTickets.has(r.id)}">${openTickets.has(r.id)?'Hide ▴':'Details ▾'}</button></div>
<div class="t-more${openTickets.has(r.id)?'':' hidden'}"><div class="facts"><div><span>Highest bet365</span><strong>${s3?esc(am(s3.high)):'—'}</strong><small>${s3?'at '+esc(time(s3.high_at)):''}</small></div><div><span>Steadiest bet365</span><strong>${s3?esc(am(s3.steadiest.odds)):'—'}</strong><small>${s3?'held '+esc(mins(s3.steadiest.seconds)):''}</small></div><div><span>Next check</span><strong>${esc(next?time(next):'—')}</strong><small>about every 10 min</small></div></div>
<p class="small">${esc((cf.reasons||[]).join(' · '))}</p>
<div class="send-foot">${b.screenshot&&!PUB?`<a href="/api/hockey/shot/${esc(b.screenshot)}" target="_blank" rel="noopener"><img class="thumb" src="/api/hockey/shot/${esc(b.screenshot)}" alt="bet365 bet slip screenshot" loading="lazy"></a>`:'<span></span>'}<span class="t-actions"><button class="mini" data-history="${esc(r.id)}">Price history</button><button class="mini owner-only" data-recheck="${esc(r.id)}">Recheck</button><button class="mini owner-only" data-track="${esc(r.id)}">Track</button></span></div></div></article>`}
function renderBoard(){const rows=parlays?.rows||[];const sets=boardSets(rows);if(!sets[boardTab])boardTab='top';
 $('boardTabs').innerHTML=BOARD_TABS.map(([k,l])=>`<button role="tab" aria-selected="${k===boardTab}" class="seg-btn${k===boardTab?' on':''}" data-tab="${k}">${l}<b>${sets[k].length}</b></button>`).join('');
 const list=sets[boardTab];const games=new Map();for(const r of list){if(!games.has(gameKey(r)))games.set(gameKey(r),{r,n:0});games.get(gameKey(r)).n++}
 if(boardGame!=='all'&&!games.has(boardGame))boardGame='all';
 $('gameChips').innerHTML=`<button class="gchip${boardGame==='all'?' on':''}" data-gchip="all">All games <b>${list.length}</b></button>`+[...games.entries()].sort((a,b)=>new Date(a[1].r.event.start_time)-new Date(b[1].r.event.start_time)).map(([k,g])=>`<button class="gchip${boardGame===k?' on':''}" data-gchip="${esc(k)}">${esc(gameLabel(g.r))} <small>${esc(time(g.r.event.start_time))}</small><b>${g.n}</b></button>`).join('');
 const shown=sortBoard(list.filter(r=>boardGame==='all'||gameKey(r)===boardGame));
 const hints={top:'Everything worth a look: confirmed first, then line 1, then the best bet365 odds. Under 3.5 from +8,000 · Under 2.5 from +30,000.',confirmed:`bet365 pays at least ${data?.rules?.minimum_payout_ratio??1.8}× FanDuel on the same four legs. These also go to Telegram / your group.`,u35:'Under 3.5 parlays at bet365 +8,000 and up (lines 1–2).',u25:'Under 2.5 parlays only when bet365 pays +30,000 or more (lines 1–2).',deep:'Lines 3–4 only with crazy odds: 3× FanDuel, or bet365 +25,000 before FanDuel posts.'};
 $('boardHint').textContent=hints[boardTab];
 $('boardGrid').innerHTML=shown.map(ticket).join('')||empty(boardTab==='confirmed'?'Nothing confirmed right now':'Nothing here yet','bet365 is pricing every forward line; parlays appear here as soon as they clear the odds floors. Prices are re-checked about every 10 minutes.');
 const n=sets.top.length;$('navQual').textContent=n||'';$('navQual').classList.toggle('hidden',!n)}
// ------------------------------------------------------------- NEW LINES POSTED banner
let linesSeen=null;try{linesSeen=localStorage.getItem('jb-lines-seen')}catch{}
function lineUpdates(){if(!data)return[];const soon=new Set((data.games||[]).filter(g=>['FUT','PRE'].includes(g.state)&&new Date(g.start_time)-Date.now()<36*3600e3).flatMap(g=>[g.home,g.away]));
 return (data.updates||[]).filter(u=>soon.has(u.team)&&Date.now()-new Date(u.observed_at)<12*3600e3)}
function linesToast(){const ups=lineUpdates();if(linesSeen===null){linesSeen=ups[0]?.observed_at||new Date().toISOString();try{localStorage.setItem('jb-lines-seen',linesSeen)}catch{}}
 const fresh=ups.filter(u=>new Date(u.observed_at)>new Date(linesSeen));const teams=[...new Set(fresh.map(u=>u.team))];
 $('navLines').classList.toggle('hidden',!teams.length);
 if(!teams.length){$('linesToast').classList.add('hidden');return}
 $('linesToastTeams').textContent=teams.map(t=>TEAMN[t]||t).join(' · ')+' · '+ago(fresh[0].observed_at);
 const wasHidden=$('linesToast').classList.contains('hidden');$('linesToast').classList.remove('hidden');
 if(wasHidden){document.title='🆕 New lines · JuneBot';try{if('Notification' in window&&Notification.permission==='granted'&&localStorage.getItem('jb-notified')!==fresh[0].observed_at){new Notification('NEW LINES POSTED',{body:teams.map(t=>TEAMN[t]||t).join(', '),tag:'junebot-lines'});localStorage.setItem('jb-notified',fresh[0].observed_at)}}catch{}}}
function linesSeenNow(){const ups=lineUpdates();linesSeen=ups[0]?.observed_at||new Date().toISOString();try{localStorage.setItem('jb-lines-seen',linesSeen)}catch{}$('linesToast').classList.add('hidden');$('navLines').classList.add('hidden');document.title='JuneBot · '+pageInfo[page()][2]}
async function showHistory(id){const r=(parlays?.rows||[]).find(x=>x.id===id);const request=++boxRequest;$('boxEyebrow').textContent='PRICE HISTORY · ACTUAL BET-SLIP QUOTES';$('boxTitle').textContent=r?takeLines(r).slice(0,3).map(t=>t.split(' — ')[0].split(' ').slice(-1)[0]).join(' / ')+` · ${r.team} U${r.total}`:'Price history';$('boxBody').textContent='Loading…';$('box').showModal();
try{const h=await get('/combo/'+id);if(request!==boxRequest)return;const st=h.stats,s3=st.bet365,sf=st.fanduel,best=st.best_ratio;
const tile=(label,val,sub)=>`<div class="hist-tile"><span>${esc(label)}</span><strong>${val}</strong><small>${sub}</small></div>`;
const rows=st.timeline.slice().reverse();
$('boxBody').innerHTML=`<div class="hist-tiles">${tile('Highest bet365',s3?esc(am(s3.high)):'—',s3?'at '+esc(time(s3.high_at)):'')}${tile('Best multiplier',best?esc(best.ratio.toFixed(2))+'×':'—',best?esc(am(best.bet365))+' vs '+esc(am(best.fanduel))+' · '+esc(time(best.at)):'')}${tile('Steadiest bet365',s3?esc(am(s3.steadiest.odds)):'—',s3?'held '+esc(mins(s3.steadiest.seconds))+' ('+esc(time(s3.steadiest.from))+'–'+esc(time(s3.steadiest.to))+')':'')}${tile('Steadiest FanDuel',sf?esc(am(sf.steadiest.odds)):'—',sf?'held '+esc(mins(sf.steadiest.seconds)):'')}</div>
<p class="small">${s3?`bet365 changed price ${s3.changes} time${s3.changes===1?'':'s'} over ${s3.checks} checks`:'No bet365 prices yet'}${sf?` · FanDuel changed ${sf.changes} time${sf.changes===1?'':'s'}`:''}. Times are Arizona.</p>
${rows.length?`<div class="table-scroll"><table><thead><tr><th>TIME</th><th>BET365</th><th>FANDUEL</th><th>MULTIPLIER</th></tr></thead><tbody>${rows.map(p=>`<tr class="${s3&&p.bet365===s3.high?'hi':''}"><td>${esc(timeS(p.at))}</td><td><strong>${esc(am(p.bet365))}</strong></td><td>${esc(am(p.fanduel))}</td><td class="${p.ratio>=3?'m-fire':p.ratio>=1.8?'m-good':'m-low'}">${esc(p.ratio.toFixed(2))}×</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">No paired prices yet.</p>'}`}catch(e){if(request===boxRequest)$('boxBody').textContent='History unavailable: '+e.message}}
function renderParlays(){if(!parlays)return;renderBoard();const rows=parlays.rows||[];const f=$('parlayFilter').value,tot=$('parlayTotal').value,q=$('parlaySearch').value.trim().toLowerCase();
const relay=data?.relay||{};const live=b=>relay[b]&&Date.now()-new Date(relay[b].last_seen)<180000;
const bannerParts=['bet365','fanduel'].map(b=>`<span class="dot ${live(b)?'on':'off'}"></span>${b==='bet365'?'bet365':'FanDuel'} relay ${live(b)?'<strong>connected</strong>'+(relay[b].state==='working'?' · pricing':''):'<strong>not connected</strong>'}`);
$('feedBanner').innerHTML=bannerParts.join('<span class="sep">·</span>')+`<span class="sep">·</span>Ratio = bet365 payout ÷ FanDuel payout. Alerts at ${esc(data?.rules?.minimum_payout_ratio??1.8)}×, 🔥 at ${esc(data?.rules?.fire_payout_ratio??3)}×.`;
let list=rows.filter(r=>(tot==='all'||String(r.total)===tot)&&(!q||JSON.stringify([r.team,r.scorer,r.assists,r.event.home,r.event.away]).toLowerCase().includes(q)));
if(f==='qualifying')list=list.filter(r=>r.category==='fire'||r.category==='qualifies');
if(f==='priced')list=list.filter(r=>r.ratio!=null);
if(f==='unconfirmed')list=list.filter(r=>r.category==='unconfirmed');
if(f==='top')list=list.filter(r=>!r.depth);if(f==='depth')list=list.filter(r=>r.depth);
if(f==='unavailable')list=list.filter(r=>['bet365','fanduel'].some(b=>!['priced','not_checked','stale'].includes(r.books[b].status)));
$('parlayCount').textContent=`${list.length} of ${rows.length} combinations`;
if(!list.length){$('parlayList').innerHTML=f==='qualifying'?empty('Nothing qualifies right now',rows.length?`${data?.counts?.priced_both||0} of ${rows.length} combinations have prices from both books so far. Switch to “All combinations” to see what is missing and why.`:'No pregame combinations yet — they appear once forward lines are posted for upcoming games.'):empty('No combinations in this view','Try another filter.');return}
const groups=new Map();for(const r of list){const k=r.event.id+'|'+r.team+'|'+r.line;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}
$('parlayList').innerHTML=[...groups.values()].map(g=>{const r0=g[0];const trio=[r0.scorer,...r0.assists];return `<article class="card parlay-group"><div class="pg-head"><div class="team-code">${esc(r0.team)}</div><div><h2>${esc(r0.event.away)} @ ${esc(r0.event.home)} <small>${esc(fmt(r0.event.start_time))}</small></h2><p class="small">${esc(r0.team)} line ${esc(r0.line)} · ${trio.map(esc).join(' · ')} ${r0.source?.lineup_kind&&r0.source.lineup_kind!=='reported'?'· '+esc(r0.source.lineup_kind):''}</p></div></div>${g.map(r=>`<div class="combo ${r.category}"><div class="combo-legs"><div><span class="leg-tag goal">G</span>${esc(r.scorer)}</div><div><span class="leg-tag ast">A</span>${esc(r.assists[0])}</div><div><span class="leg-tag ast">A</span>${esc(r.assists[1])}</div><div><span class="leg-tag tot">U</span>${esc(r.team)} under ${esc(r.total)}</div></div>${bookCell('bet365',r.books.bet365)}${bookCell('FanDuel',r.books.fanduel)}<div class="combo-side">${ratioBadge(r)}${r.confidence?`<small class="conf-chip conf-${esc(r.confidence.level.toLowerCase())}">${esc(r.confidence.level)} conf.</small>`:''}${r.note?`<small>${esc(r.note)}</small>`:''}<div class="combo-actions"><button class="mini" data-history="${esc(r.id)}">History</button><button class="mini owner-only" data-recheck="${esc(r.id)}">Recheck</button><button class="mini owner-only" data-track="${esc(r.id)}">Track</button></div></div></div>`).join('')}</article>`}).join('')}

// ------------------------------------------------------------- games
function renderGames(){if(!data)return;const today=azDate(Date.now());const mode=$('gameFilter').value;const now=Date.now();
const reports=new Map(data.reports.filter(usable).map(r=>[r.team,r]));
const games=data.games.filter(g=>mode==='all'||mode==='today'&&azDate(g.start_time)===today||mode==='upcoming'&&['FUT','PRE'].includes(g.state)&&new Date(g.start_time)>now-3600e3||mode==='live'&&['LIVE','CRIT'].includes(g.state)||mode==='final'&&['OFF','FINAL'].includes(g.state));
const list=mode==='upcoming'?games.slice(0,40):games;$('gameCount').textContent=`${list.length} ${list.length===1?'game':'games'}`;
const lineChip=t=>{const r=reports.get(t);return r?`<span class="chip ok">${esc(t)} lines · ${esc(r.source?.lineup_kind==='projected'?'projected':r.source?.lineup_kind||'reported')}</span>`:`<span class="chip">${esc(t)} lines pending</span>`};
$('gameCards').innerHTML=list.map(g=>`<article class="card game-card"><div class="meta"><span>${esc(fmt(g.start_time))}</span><span class="badge">${esc(stateName(g.state))}</span></div><div class="match">${esc(g.away)} <small>AT</small> ${esc(g.home)}</div><div class="meta"><span>${g.away_score==null||g.home_score==null?'Score pending':`${Number(g.away_score)} — ${Number(g.home_score)}`}</span><span>Arizona time</span></div>${['FUT','PRE'].includes(g.state)?`<div class="chips">${lineChip(g.away)}${lineChip(g.home)}</div>`:''}<button class="button" data-game="${esc(g.id)}" aria-label="Box score for ${esc(g.away)} at ${esc(g.home)}">View box score ↗</button></article>`).join('')||empty('No games in this view','Choose another schedule filter.')}

// ------------------------------------------------------------- results
const LEG_ICON={reached:'✓',under_final:'✓',under_so_far:'…',pending:'…',over_limit:'✕',not_reached_final:'✕',unknown:'?'};
async function renderResults(){const box=$('resultList');try{const r=await get('/results');const f=$('resultFilter').value;let w=r.watched||[];
w=w.filter(x=>f==='all'||(f==='done'?['stats_met','stats_not_met','needs_review'].includes(x.progress.status):!['stats_met','stats_not_met','needs_review'].includes(x.progress.status)));
$('resultCount').textContent=`${w.length} tracked`;
box.innerHTML=w.map(x=>{const c=x.candidate,p=x.progress;const st={pregame:'Pregame',live:'Live',live_partial_data:'Live',stats_met:'All legs hit',stats_not_met:'Missed',needs_review:'Needs review',awaiting_game_data:'Waiting'}[p.status]||p.status;
const legs=(p.legs&&p.legs.length?p.legs:c.legs.map(l=>({label:l.market==='team_total_goals'?`${c.team} Under ${l.line} goals`:`${l.player_id.split('_').slice(0,-2).join(' ')} 1+ ${l.market==='player_goals'?'goals':'assists'}`,status:'pending',value:null})));
return `<article class="card result ${esc(p.status)}"><div class="pg-head"><div class="team-code">${esc(c.team)}</div><div><h2>${esc(c.event.away)} @ ${esc(c.event.home)} <small>${esc(fmt(c.event.start_time))}</small></h2><p class="small">${esc(p.score||'')} ${x.accepted_odds?'· bet365 '+esc(am(x.accepted_odds))+' when alerted':''}</p></div><span class="badge ${p.status==='stats_met'?'':'muted-badge'}">${esc(st)}</span></div><ul class="legs">${legs.map(l=>`<li class="leg ${esc(l.status)}"><span>${LEG_ICON[l.status]||'…'}</span>${esc(l.label)}${l.value!=null?` <small>(${esc(l.value)})</small>`:''}</li>`).join('')}</ul><div class="card-footer"><span>${esc(p.note||'Official full-game statistics; not sportsbook settlement.')}</span><button class="mini owner-only" data-untrack="${esc(x.id)}">Remove</button></div></article>`}).join('')||empty('Nothing tracked yet','Alerted combinations are tracked automatically; you can also press Track on any parlay.')}catch(e){box.innerHTML=empty('Results unavailable',e.message)}}

// ------------------------------------------------------------- history
async function renderHistory(){try{const h=await get('/history');
$('scanList').innerHTML=h.scans.slice(0,120).map(s=>`<div class="log ${esc(s.kind)}"><time>${esc(fmt(s.at))}</time><span>${esc(s.summary)}</span></div>`).join('')||'<p class="small">No scans yet.</p>';
$('updateList').innerHTML=h.updates.map(u=>`<div class="log"><time>${esc(fmt(u.observed_at))}</time><span><strong>${esc(u.team)}</strong> ${u.kind==='new_team_report'?'new report':'updated report'} · ${esc(u.line_count)} lines ${u.source?.url?`· <a href="${esc(safeURL(u.source.url))}" target="_blank" rel="noopener">source ↗</a>`:''}</span></div>`).join('')||'<p class="small">No changes recorded since JuneBot started.</p>';
$('quoteList').innerHTML=h.quotes.map(q=>`<div class="log ${q.status==='priced'?'ok':q.status==='connection_error'?'error':''}"><time>${esc(timeS(q.received_at))}</time><span><strong>${esc(q.book==='bet365'?'bet365':'FanDuel')}</strong> · ${esc(STATUS[q.status]||q.status)}${q.american_odds!=null?' '+esc(am(q.american_odds)):''}${q.missing?.length?' — '+esc(q.missing.map(m=>(m.player||m.team||'')+' '+m.reason).join('; ')):''}${q.detail&&q.status!=='priced'?' · '+esc(q.detail):''}</span></div>`).join('')||'<p class="small">No sportsbook checks yet. Connect the Quote Relay (Status page).</p>';
$('alertList').innerHTML=h.alerts.map(a=>`<div class="log ${a.delivered?'ok':'error'}"><time>${esc(fmt(a.sent_at))}</time><span>${a.category==='lines'?'🆕 New lines posted':a.category==='board'?'🟡 New on the board · bet365 '+esc(am(a.bet365)):`${a.category==='fire'?'🔥 ':''}${esc(a.ratio?.toFixed?.(2))}× · bet365 ${esc(am(a.bet365))} / FD ${esc(am(a.fanduel))}`} ${a.delivered?'':'· not delivered: '+esc(a.error)}<details><summary>Message</summary><pre>${esc((a.message||'').replace(/<[^>]+>/g,''))}</pre></details></span></div>`).join('')||'<p class="small">No alerts sent yet.</p>'}catch(e){$('scanList').innerHTML=empty('History unavailable',e.message)}}

// ------------------------------------------------------------- sources
function srcCard(title,badge,cls,body,extra){return `<article class="card source-card"><span class="badge ${cls}">${esc(badge)}</span><h2>${esc(title)}</h2><p>${body}</p>${extra||''}</article>`}
function renderSources(){if(!data)return;const s=data.sources||{},relay=data.relay||{},tg=data.telegram||{};
const src=(k,title,desc)=>{const x=s[k];return srcCard(title,!x?'NOT CHECKED':x.ok?'CONNECTED':'CHECK NEEDED',!x?'muted-badge':x.ok?'':'warn-badge',desc,`<div class="source-note">${x?esc((x.ok?'':'Problem: ')+x.detail)+' · '+esc(ago(x.at)):'Waiting for the first check.'}</div>`)};
const rel=b=>{const r=relay[b];const live=r&&Date.now()-new Date(r.last_seen)<180000;const name=b==='bet365'?'bet365':'FanDuel';
return srcCard(name+' bet slip (Quote Relay)',live?(r.state==='error'?'RELAY ERROR':'CONNECTED'):'NOT CONNECTED',live?(r.state==='error'?'warn-badge':''):'muted-badge',`Actual combined ${name} prices read from your own bet slip in Chrome (Arizona).`,`<div class="source-note">${r?`Last seen ${esc(ago(r.last_seen))}${r.signed_in===false?' · appears signed out':''}${r.note?' · '+esc(r.note):''}`:'Install the extension and turn on Auto-price.'}</div>`)};
const macCard=PUB?(()=>{const age=pubAge(),off=data.mac==='stopped'||age>5;return srcCard('JuneBot Mac',off?(data.mac==='stopped'?'STOPPED':'OFFLINE'):'ONLINE',off?'warn-badge':'',off?(data.mac==='stopped'?'JuneBot was closed on the Mac.':'No updates from the Mac. It may be asleep, shut down or off the internet.'):'The Mac is running JuneBot and updating this board every minute.',`<div class="source-note">Last update ${esc(fmt(data.published_at))} Arizona · ${esc(ago(data.published_at))}</div>`)})():'';
$('sourceGrid').innerHTML=macCard+src('gamedaytweets','GameDayTweets lines','Primary forward-line source. Checked every 5 minutes, every 2 minutes when a game starts within 3 hours.')+src('nhl_schedule','Official NHL schedule','Games, start times, scores and box scores.')+src('dailyfaceoff','Daily Faceoff (backup)','Projected lines for teams playing within 12 hours without a GameDayTweets report.')+rel('bet365')+rel('fanduel')+src('fanduel_api','FanDuel market check','Confirms posted markets so “lines not out yet” is shown only when FanDuel confirms it. Not a price source.')+(PUB?'':srcCard('Telegram',tg.configured?(data.settings?.alerts_enabled?'ON':'PAUSED'):'NOT CONFIGURED',tg.configured&&data.settings?.alerts_enabled?'':'muted-badge','Qualifying combinations, fully written out with both books’ prices and check times; bet365 slip screenshot when available.',`<div class="source-note">${tg.last_sent?'Last alert '+esc(ago(tg.last_sent)):'No alerts sent yet'}${tg.last_error?' · Last error: '+esc(tg.last_error):''}</div>`));
$('setAlerts').checked=!!data.settings?.alerts_enabled;$('setFdApi').checked=!!data.settings?.fanduel_api;$('setDf').checked=!!data.settings?.dailyfaceoff;
const pub=data.public||{};$('publicState').innerHTML=pub.url?`<strong>Link:</strong> <a href="${esc(safeURL(pub.url))}" target="_blank" rel="noopener">${esc(pub.url)}</a><br>${pub.error?'<span style="color:var(--warn)">Last push failed: '+esc(pub.error)+'</span>':pub.last_push?'Last updated '+esc(ago(pub.last_push)):'Publishing…'}`:(pub.connected?(pub.error?'<span style="color:var(--warn)">'+esc(pub.error)+'</span>':'Setting up the page…'):'Not connected yet.');$('publicConnect').classList.toggle('hidden',!!pub.connected&&!pub.error);
const im=data.imessage||{};$('imState').innerHTML=!im.available?'Works only on the Mac running JuneBot.':im.chat_id?`<strong>Group:</strong> ${esc(im.label||im.chat_id)} · ${im.enabled?'texting on':'texting off'}${im.last_sent?' · last text '+esc(ago(im.last_sent)):''}${im.last_error?'<br><span style="color:var(--warn)">'+esc(im.last_error)+'</span>':''}`:'No group picked yet — press “Find my group chats”.';
for(const [id,k] of [['imEnabled','enabled'],['imLines','lines'],['imBoard','board'],['imParlays','parlays'],['imUpdates','updates']])$(id).checked=!!im[k];
const r=data.rules||{};$('rulesNote').textContent=`Rules: alert at ${r.minimum_payout_ratio}× FanDuel's payout, 🔥 Fire at ${r.fire_payout_ratio}×, +${(r.preferred_american_odds||10000).toLocaleString()} is a preference only. Both quotes must be under ${r.alert_max_quote_age_seconds}s old and within ${r.alert_max_quote_skew_seconds}s of each other; JuneBot rechecks both books automatically before alerting.`}

// ------------------------------------------------------------- data loading
async function refresh(){try{data=await get('');renderTop();if(page()==='parlays')await loadParlays();if(data.refreshing){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,2000)}}catch(e){$('health').textContent=PUB?'Live data is unavailable right now — retrying every minute.':'JuneBot is disconnected from its local server. Reopen Open JuneBot.command to reconnect.';$('health').classList.remove('hidden');$('refreshSources').disabled=false}}
async function loadParlays(){try{parlays=await get('/parlays');renderParlays()}catch(e){$('parlayList').innerHTML=empty('Parlays unavailable',e.message)}}
function loadPage(){const p=page();if(p==='parlays')loadParlays();if(p==='results')renderResults();if(p==='history')renderHistory()}
$('search').oninput=renderTop;$('lineupScope').onchange=renderTop;$('gameFilter').onchange=renderGames;$('resultFilter').onchange=renderResults;
['parlayFilter','parlayTotal'].forEach(id=>$(id).onchange=renderParlays);$('boardSort').onchange=()=>{try{localStorage.setItem('jb-sort',$('boardSort').value)}catch{}renderBoard()};
$('linesToastView').onclick=()=>{linesSeenNow();location.hash='#lineups'};$('linesToastClose').onclick=linesSeenNow;
$('linesToastBell').onclick=async()=>{try{if(!('Notification' in window))throw Error('This browser has no pop-up notifications');const p=await Notification.requestPermission();$('linesToastBell').textContent=p==='granted'?'🔔✓':'🔕'}catch(e){alert(e.message)}};$('parlaySearch').oninput=renderParlays;
$('refreshSources').onclick=async()=>{try{$('refreshSources').disabled=true;$('refreshLabel').textContent='Checking…';await post('/refresh');await refresh()}catch(e){$('health').textContent=e.message;$('health').classList.remove('hidden');$('refreshSources').disabled=false;$('refreshLabel').textContent='Refresh'}};
$('showKey').onclick=async()=>{try{const r=await post('/relay-key');$('relayKey').textContent=r.relay_key;$('relayKey').classList.remove('hidden')}catch(e){$('relayKey').textContent=e.message;$('relayKey').classList.remove('hidden')}};
$('ghSave').onclick=async()=>{$('ghMsg').textContent='Connecting…';try{await post('/github-token',{token:$('ghToken').value});$('ghToken').value='';$('ghMsg').textContent='Connected — the link appears here in about a minute.';setTimeout(refresh,8000)}catch(e){$('ghMsg').textContent=e.message}};
$('imFind').onclick=async()=>{$('imMsg').textContent='Asking Messages for your chats… (approve the macOS prompt if it appears)';try{const r=await post('/imessage-chats');const sel=$('imChats');
 sel.innerHTML=r.chats.map(c=>`<option value="${esc(c.id)}" data-label="${esc(c.name||c.people.join(', '))}">${c.group?'👥 ':''}${esc(c.name||c.people.slice(0,4).join(', ')+(c.people.length>4?' +'+(c.people.length-4):''))}</option>`).join('');
 sel.classList.remove('hidden');$('imSave').classList.remove('hidden');$('imMsg').textContent=r.chats.length?`${r.chats.length} chats found — pick your group and press “Use this chat”.`:'No chats found in Messages.'}catch(e){$('imMsg').textContent=e.message}};
$('imSave').onclick=async()=>{const o=$('imChats').selectedOptions[0];if(!o)return;try{await post('/imessage-settings',{chat_id:o.value,label:o.dataset.label,enabled:true});$('imMsg').textContent='Saved. Press “Send test to group” to check.';await refresh()}catch(e){$('imMsg').textContent=e.message}};
for(const [id,k] of [['imEnabled','enabled'],['imLines','lines'],['imBoard','board'],['imParlays','parlays'],['imUpdates','updates']])$(id).onchange=async e=>{try{await post('/imessage-settings',{[k]:e.target.checked});await refresh()}catch(err){$('imMsg').textContent=err.message}};
$('imTest').onclick=async()=>{$('imMsg').textContent='Sending…';try{await post('/imessage-test');$('imMsg').textContent='Sent — check the group.'}catch(e){$('imMsg').textContent=e.message}};
$('tgTest').onclick=async()=>{$('tgMsg').textContent='Sending…';try{await post('/telegram-test');$('tgMsg').textContent='Sent. Check Telegram.'}catch(e){$('tgMsg').textContent=e.message}};
for(const [id,key] of [['setAlerts','alerts_enabled'],['setFdApi','fanduel_api'],['setDf','dailyfaceoff']])$(id).onchange=async e=>{try{await post('/settings',{[key]:e.target.checked});await refresh()}catch(err){alert(err.message)}};
$('closeBox').onclick=()=>$('box').close();
document.addEventListener('click',async e=>{
 const hb=e.target.closest('[data-history]');if(hb){showHistory(hb.dataset.history);return}
 const tb=e.target.closest('[data-tab]');if(tb){boardTab=tb.dataset.tab;boardGame='all';try{localStorage.setItem('jb-tab',boardTab)}catch{}renderBoard();return}
 const gc=e.target.closest('[data-gchip]');if(gc){boardGame=gc.dataset.gchip;renderBoard();return}
 const ex=e.target.closest('[data-expand]');if(ex){const more=ex.closest('.ticket').querySelector('.t-more');const open=more.classList.toggle('hidden')===false;ex.setAttribute('aria-expanded',open);ex.textContent=open?'Hide ▴':'Details ▾';(open?openTickets.add(ex.dataset.expand):openTickets.delete(ex.dataset.expand));return}
 const t=e.target.closest('[data-track],[data-untrack],[data-recheck]');
 if(t){try{if(t.dataset.track){await post('/track',{candidate_id:t.dataset.track});t.textContent='Tracked ✓'}if(t.dataset.untrack){await post('/untrack',{candidate_id:t.dataset.untrack});renderResults()}if(t.dataset.recheck){await post('/recheck',{candidate_id:t.dataset.recheck});t.textContent='Queued ✓'}}catch(err){t.textContent=err.message.slice(0,40)}return}
 const b=e.target.closest('[data-game]');if(!b)return;const g=data.games.find(x=>x.id===b.dataset.game);if(!g)return;const request=++boxRequest;$('boxEyebrow').textContent='OFFICIAL NHL BOX SCORE';$('boxTitle').textContent=`${g.away} at ${g.home}`;$('boxBody').textContent='Loading official statistics…';$('box').showModal();
 try{const score=await get('/boxscore/'+g.id);if(request!==boxRequest)return;$('boxBody').innerHTML=`<p class="small">${esc(stateName(score.state))} · Checked ${esc(fmt(score.observed_at))} Arizona</p>${score.teams.map(t=>`<div class="box-team"><h2>${esc(t.team)} <span class="badge">${t.score==null?'Score pending':Number(t.score)+' goals'}</span></h2>${t.skaters.length?`<div class="table-scroll"><table><thead><tr><th>PLAYER</th><th>GOALS</th><th>ASSISTS</th><th>SHOTS</th><th>ICE TIME</th></tr></thead><tbody>${t.skaters.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.goals??'—')}</td><td>${esc(p.assists??'—')}</td><td>${esc(p.shots??'—')}</td><td>${esc(p.time_on_ice??'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="small">Player statistics have not been posted yet.</p>'}</div>`).join('')}<p class="small" style="margin-top:24px">${esc(score.note)}</p>`}catch(err){if(request===boxRequest)$('boxBody').textContent='Box score unavailable: '+err.message}});
try{$('motionToggle').checked=localStorage.getItem('junebot-motion')!=='off'}catch{}function motion(){document.body.classList.toggle('motion-off',!$('motionToggle').checked)}motion();$('motionToggle').onchange=()=>{motion();try{localStorage.setItem('junebot-motion',$('motionToggle').checked?'on':'off')}catch{}};
try{const saved=localStorage.getItem('junebot-scope');if(saved)$('lineupScope').value=saved;$('lineupScope').addEventListener('change',()=>{try{localStorage.setItem('junebot-scope',$('lineupScope').value)}catch{}})}catch{}
showPage();if(PUB&&PUBDATA){data=Object.assign({},PUBDATA.hockey,{published_at:PUBDATA.published_at,mac:PUBDATA.mac});renderTop();loadPage()}refresh();setInterval(()=>{if(!document.hidden){refresh();const p=page();if(p==='results')renderResults();if(p==='history')renderHistory()}},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
